### ISSUE TITLE
missing capsblock.exe?

### ISSUE THREAD

**Issue by hrafnblod** [jdknight/capsblock#1]
Hi, i dont seem to be able to use this. ive unpacked the zip and run the install.bat, however, there is no capsblock.exe to be found anywhere, and when i reboot my machine, there is no capsblock process running.
windows 10 Pro 10.0.19045.
was i supposed to compile it first?
regards

**Comment by jdknight** [comment]
The release process does [build an executable](https://github.com/jdknight/capsblock/actions/runs/7951496140/job/21704987041#step:3:39) and should exist in the portable package produced by the GitLab action:

![image](https://github.com/jdknight/capsblock/assets/1834509/6b67e66d-5b03-4699-ba2e-2c40450e8427)

The only assumption I have is possibly security-related tools maybe preventing the extraction of the executable?

**Comment by jdknight** [comment]
Added a pinned issue (https://github.com/jdknight/capsblock/issues/3) explaining a missing executable scenario. Hopefully this is good enough to provide some insight. No idea what a perfect solution is to avoid such scenarios. I appreciate the feedback and will try to always sanity check with popular security software to see if any false-positive detections exist, and try to send submissions to address it.
